// <auto-generated />
namespace Reactive.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Map : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Map));
        
        string IMigrationMetadata.Id
        {
            get { return "201501230328165_Map"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
